import React from 'react';
import './styles/background.css';

// @ts-ignore
const Subcomponent = ({ hasTopWall, hasBottomWall, hasLeftWall, hasRightWall, hasDot }) => {
    const subcomponentClasses = `subcomponent ${hasDot ? 'with-dot' : ''} ${
        hasTopWall ? 'has-top-wall' : ''
    } ${hasBottomWall ? 'has-bottom-wall' : ''} ${hasLeftWall ? 'has-left-wall' : ''} ${
        hasRightWall ? 'has-right-wall' : ''
    }`;

    return (
        <div className={subcomponentClasses}>
            {hasDot && <div className="dot"/>}
        </div>
    );
};

const Background = () => {
    const grid = [
        [
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
        ],
        [
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
        ],
        [
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: true, hasRightWall: false, hasDot: true },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: true, hasDot: true },
        ],
        [
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: true, hasRightWall: false, hasDot: false },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: true, hasRightWall: false, hasDot: false },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: true, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: true, hasRightWall: true, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: true, hasRightWall: false, hasDot: false },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: true, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: true, hasRightWall: true, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: true, hasRightWall: false, hasDot: false },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: true, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: true, hasRightWall: true, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: true, hasDot: true },
        ],
        [
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: true, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: true, hasRightWall: false, hasDot: false },
            { hasTopWall: true, hasBottomWall: true, hasLeftWall: true, hasRightWall: true, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: true, hasDot: false },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: true, hasRightWall: true, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: true, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: true, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: true, hasRightWall: true, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: true, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: false, hasRightWall: true, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: true, hasRightWall: true, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: true, hasDot: true },
        ],
        [
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: true, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: true, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: false, hasRightWall: true, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: true, hasBottomWall: true, hasLeftWall: true, hasRightWall: true, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: true, hasRightWall: true, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: true, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: true, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: true, hasDot: true },
        ],
        [
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: true, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: true, hasRightWall: true, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: true, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: true, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: true, hasBottomWall: true, hasLeftWall: true, hasRightWall: false, hasDot: false },
            { hasTopWall: true, hasBottomWall: true, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: true, hasBottomWall: true, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: true, hasBottomWall: true, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: true, hasBottomWall: true, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: true, hasBottomWall: true, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: true, hasBottomWall: true, hasLeftWall: false, hasRightWall: true, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: true, hasDot: true },
        ],
        [
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: true, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: false, hasRightWall: true, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: true, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: true, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: true, hasDot: true },
        ],
        [
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: true, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: true, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: false, hasRightWall: true, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: true, hasRightWall: false, hasDot: false },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: true, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
        ],
        [
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: true, hasRightWall: false, hasDot: true },
            { hasTopWall: true, hasBottomWall: true, hasLeftWall: true, hasRightWall: false, hasDot: false },
            { hasTopWall: true, hasBottomWall: true, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: true, hasBottomWall: true, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: true, hasBottomWall: true, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: true, hasBottomWall: true, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: true, hasBottomWall: true, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: true, hasBottomWall: true, hasLeftWall: false, hasRightWall: true, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: true, hasRightWall: true, hasDot: false },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: true, hasDot: true },
        ],
        [
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: true, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: true, hasRightWall: false, hasDot: false },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: true, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: true, hasRightWall: true, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: true, hasBottomWall: true, hasLeftWall: true, hasRightWall: true, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: true, hasRightWall: false, hasDot: false },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: true, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: true, hasDot: true },
        ],
        [
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: true, hasRightWall: false, hasDot: true },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: true, hasRightWall: true, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: true, hasRightWall: false, hasDot: false },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: false, hasRightWall: true, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: true, hasBottomWall: false, hasLeftWall: true, hasRightWall: true, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: true, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: true, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: true, hasRightWall: true, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: true, hasRightWall: false, hasDot: false },
            { hasTopWall: true, hasBottomWall: true, hasLeftWall: true, hasRightWall: true, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: true, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: true, hasDot: true },
        ],
        [
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: true, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: true, hasRightWall: true, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: true, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: false, hasRightWall: true, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: true, hasRightWall: true, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: true, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: false, hasRightWall: true, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: true, hasRightWall: true, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: true, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: false, hasRightWall: false, hasDot: false },
            { hasTopWall: false, hasBottomWall: true, hasLeftWall: false, hasRightWall: true, hasDot: false },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: true, hasDot: false },
        ],
        [
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: true, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: false, hasDot: true },
            { hasTopWall: false, hasBottomWall: false, hasLeftWall: false, hasRightWall: true, hasDot: true },
        ],
    ];

    return (
        <div className="pacman-background">
            {grid.map((row, rowIndex) => (
                <div key={rowIndex} className="row">
                    {row.map((subcomponentProps, columnIndex) => (
                        <Subcomponent
                            key={columnIndex}
                            {...subcomponentProps}
                        />
                    ))}
                </div>
            ))}
        </div>
    );
};

export default Background;